# Generated by Django 5.1.4 on 2025-03-20 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InformationModel',
            fields=[
                ('sku', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('title', models.CharField(max_length=50)),
                ('auther', models.CharField(max_length=55)),
                ('controler', models.CharField(max_length=10)),
                ('controler_model', models.CharField(max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='media/%y/%m/%d')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
